version: '3.5'

services:
  postgresql:
    image: "postgres:alpine"
    container_name: "postgresql"
    restart: always
    env_file:
      - configs/posrgersql-database.env # configure postgres
    volumes:
      - database-repository:/var/lib/postgresql/repository # persist repository locally even if container shuts down
    ports:
      - 5432:5432
    expose:
      - 5432

volumes:
  database-repository: # database named volume